# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 07:48:38 2018 from module list in Acme::CPANLists::Import::PerlAdvent::2000_12_01 version 0.001.

package Acme::CPANModules::Import::PerlAdvent::2000_12_01;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [http://perladvent.org/2000/1/] (retrieved on 2016-11-07). Visit the URL for the full contents.",
  entries     => [{ module => "Data::Dumper" }],
  summary     => "Modules mentioned in Perl Advent Calendar 2000 (day 1)",
};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2000 (day 1)

