# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 07:48:38 2018 from module list in Acme::CPANLists::Import::PerlAdvent::2000_12_02 version 0.001.

package Acme::CPANModules::Import::PerlAdvent::2000_12_02;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [http://perladvent.org/2000/2/] (retrieved on 2016-11-07). Visit the URL for the full contents.",
  entries     => [
                   { module => "HTTP::Status" },
                   { module => "LWP::UserAgent" },
                   { module => "LWP::Simple" },
                 ],
  summary     => "Modules mentioned in Perl Advent Calendar 2000 (day 2)",
};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2000 (day 2)

